name: Run Code

on: [push]

jobs:
  save-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # - name: Checkout
      # - uses: actions/checkout@v6
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: actions/checkout@v6

      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

      # - uses: actions/checkout@v6

      - name: Install bun
        run: |
          curl -fsSL https://bun.com/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          echo "BUN_INSTALL_DIR=$HOME/.bun" >> $GITHUB_ENV

      - run: bun main.ts
